/*
 * This Java source file was generated by the Gradle 'init' task.
 */

/**
 * TODO:create MyCrawler and Controller
 */

package crawler;

import java.util.ArrayList;

public class App {
    public static void main(String[] args) throws Exception {
        ArrayList<String> priceList =
                new Parser("https://vancouver.craigslist.org/search/sss?query=playstation+4+pro&sort=rel")
                        .getElementsByClass("result-price");

        for (String price: priceList) {
            System.out.println(price);
        }
    }

}
