/*
 * This Java source file was generated by the Gradle 'init' task.
 */

/**
 * TODO:create MyCrawler and Controller
 */

package crawler;

import com.example.crawler.crawler.MyCrawler;

import edu.uci.ics.crawler4j.crawler.Page;
import edu.uci.ics.crawler4j.url.WebURL;
import edu.uci.ics.crawler4j.crawler.WebCrawler;
import edu.uci.ics.crawler4j.parser.HtmlParseData;

public class App {
    public String getGreeting() {
        return "Done";
    }

    public static void main(String[] args) {
        MyCrawler myCrawler = new MyCrawler();
        WebURL webURL = new WebURL();
        webURL.setURL("https://vancouver.craigslist.org");
        Page page = new Page(webURL);
        myCrawler.visit(page);
        System.out.println(new App().getGreeting());
    }
}
